### PR TITLE
disabled all fonts

### PR DESCRIPTION
**Pull request by wheresrhys**
For this https://github.com/Financial-Times/n-layout/pull/45

### CODE REVIEW

**Comment by keirog** [comment]
Ah, tests

**Comment by keirog** [comment]
:+1: Once they're err… fixed

**Comment by keirog** [comment]
Oh hang on… doesn't this wipe out the fallbacks?

**Comment by wheresrhys** [comment]
It turns out that o-typography is the only origami module - by design - that forcibly downloads custom fonts. But there's an issue to possibly allow turning it off https://github.com/Financial-Times/o-typography/issues/63

**Pull request closed without merging**
