### PR TITLE
Do not display focus outline on non-interactive elements

### PR DESCRIPTION
**Pull request by mmockett**
@i-like-robots 

This has come from an editorial desire.

### CODE REVIEW

**Comment by mmockett** [comment]
@i-like-robots passed!

**Comment by keirog** [comment]
:-1: I strongly disagree with this change. Am going to visit tomorrow with loads of toys and a pram

**Comment by commuterjoy** [comment]
@keirog accessiblity?

**Comment by mmockett** [comment]
Just for context, this change has come from a quirk in fastFT (open in stream): when clicking on 'Show More' on the article in-stream, we switch focus to the expanded article view, which creates a jarring dotted border around the article:

articleborder

Editorial think that this looks odd and confusing, and so to avoid this we have hidden the bordered focus state when it is forcibly shifted to the article.

Though this may impact people using a keyboard to navigate the site, the impact should be minimal - their next tab will take them to the in-article copyright link or else the first link in the article body if there is one.

Having said that, if this generates user complaints, it will give us a case to justify the presence of the visible focus state to editorial. My opinion is that it shouldn't have a practical impact on accessibility, and it benefits the majority of users in displaying a cleaner / less confusing experience. But if I've missed the point, let me know.

**Comment by mmockett** [comment]
We'll reconsider the design of this page so that it makes logical sense and avoids this workaround.

**Comment by keirog** [comment]
@commuterjoy yep.
@mmockett Just to document our offline conversation, the concerns were:
- this is a blanket change for a specific problem, which would likely have negative repercussions on accessibility/usability
- this is only a problem because the design doesn't consider focus states. I'm not convinced we've explored all the alternatives
- if it's decided that editorial should have the power to disregard accessibility, it'd be preferable to only apply the rule to these specific elements

**Pull request closed without merging**
